version: '3.8'

services:
  mysql:
    container_name: mysql
    build:
      context: ./mysql
      dockerfile: .
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=3141592
      - MYSQL_DATABASE=mqtt
      - MYSQL_USER=mqtt
      - MYSQL_PASSWORD=mqttpassword
    networks:
      backend_net:
    ports:
      - 3306:3306
    healthcheck:
      test: mysql --user=root --password=$$MYSQL_ROOT_PASSWORD -e 'select count(*) from mqtt.dispositivo' mqtt

  mosquitto:
    build:
      context: ./mosquitto
      dockerfile: .
    container_name: mosquitto
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883
      - 8883:8883
    networks:
      backend_net:
    depends_on:
      mysql:
        condition: service_healthy
  backend:
    build:
      context: ./backend
      dockerfile: .
    container_name: backend
    ports:
      - 8080:8080
    environment:
      - MOSQUITTO_HOST=mosquitto
      - MYSQL_HOST=mysql
    networks:
      backend_net:
    depends_on:
      - mysql
      - mosquitto
    healthcheck:
      test: wget -S -O - http://localhost:8080/health 2>&1 | head -n 5 | grep 204 || exit 1
      interval: 15s
      timeout: 30s
      retries: 5
      start_period: 20s
networks:
  backend_net:
    driver: bridge