version: '3.8'

services:
  mqtt-server:
    build: 
      context: ./mosquitto
      dockerfile: .
    ports:
      - 1883:1883
      - 8883:8883
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
